version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge